---

- name: Clean up after ourselves
  file:
    path: "{{item}}"
    state: "absent"
  with_items:
    - "/tmp/Python-{{autologic_python_version}}.tgz"
    - "/tmp/Python-{{autologic_python_version}}"
