---

- include: prechecks.yml
- include: dependencies.yml
  when:
    - autologic_python_manage_deps
    - not have_setuptools|bool or not have_python|bool

- include: python.yml
  when:
    - not have_python|bool

- include: path.yml
  when:
    - autologic_python_manage_path

- include: pip.yml
  when:
    - autologic_python_manage_pip
    - not have_pip|bool

- include: virtualenv.yml
  when:
    - autologic_python_manage_virtualenv
    - not have_virtualenv|bool 

- include: cleanup.yml
  when:
    - not have_python|bool

