---

- name: Pre-fetch Check (python)
  stat:
    path: "/tmp/Python-{{autologic_python_version}}.tgz"
    get_md5: false 
  register: fetch_python

- name: Fetch (python)
  get_url:
    url: "https://www.python.org/ftp/python/{{autologic_python_version}}/Python-{{autologic_python_version}}.tgz"
    dest: "/tmp"
  when: not fetch_python.stat.exists

- name: Extract (python)
  unarchive:
    copy: false 
    src: "/tmp/Python-{{autologic_python_version}}.tgz"
    dest: "/tmp/"
    creates: "/tmp/Python-{{autologic_python_version}}"


- name: Build and Install (python)
  shell: "./configure --prefix=/usr/local && make install"
  args:
    creates: "/usr/local/bin/python{{autologic_python_version[:3]}}"
    chdir: "/tmp/Python-{{autologic_python_version}}"